// Parsed student data from Google Spreadsheet
// Fields: full_name, email, phone, weight, height, birth_date, physical_activity, objective, current_protocol, comorbidities

function parseHeight(val: string | undefined): number | null {
  if (!val || val.trim() === "") return null;
  const n = parseFloat(val.replace(",", "."));
  if (isNaN(n)) return null;
  // If value is less than 3, it's in meters, convert to cm
  return n < 3 ? Math.round(n * 100) : Math.round(n);
}

function parseWeight(val: string | undefined): number | null {
  if (!val || val.trim() === "") return null;
  const cleaned = val.replace(",", ".").replace(/[^\d.]/g, "");
  const n = parseFloat(cleaned);
  return isNaN(n) ? null : Math.round(n * 10) / 10;
}

function parseBirthDate(val: string | undefined): string | null {
  if (!val || val.trim() === "") return null;
  // Check if it's a date format like "4/28/1997" or "10/12/1989"
  const dateMatch = val.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (dateMatch) {
    const [, month, day, year] = dateMatch;
    return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
  }
  // It's likely an age number
  const age = parseInt(val);
  if (!isNaN(age) && age > 0 && age < 120) {
    const birthYear = new Date().getFullYear() - age;
    return `${birthYear}-01-01`;
  }
  return null;
}

function cleanPhone(val: string | undefined): string {
  if (!val || val.trim() === "") return "";
  const digits = val.replace(/\D/g, "");
  if (digits.length < 10) return "";
  if (digits.length === 11) return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`;
  if (digits.length === 10) return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`;
  return digits;
}

interface RawRow {
  timestamp: string;
  email: string;
  full_name: string;
  peso: string;
  nascimento: string;
  altura: string;
  atividade: string;
  medicamentos: string;
  comorbidades: string;
  objetivo: string;
  telefone: string;
}

export interface ParsedStudent {
  full_name: string;
  email: string;
  phone: string;
  weight: number | null;
  height: number | null;
  birth_date: string | null;
  physical_activity: string;
  objective: string;
  current_protocol: string;
  comorbidities: string;
}

// Raw data extracted from the spreadsheet
const rawData: RawRow[] = [
  { timestamp: "9/1/2024", email: "luanarequena@gmail.com", full_name: "Luana carla melo requena", peso: "64", nascimento: "40", altura: "161", atividade: "Musculação 2hs, Bicicleta 30min", medicamentos: "Sulpemento(ÉvoraPW, creatina, iso-x protein), medicamento (aradois 50mg), hormonio (durateston)", comorbidades: "Nao", objetivo: "Crescimento muscular", telefone: "" },
  { timestamp: "9/2/2024", email: "wvalemao@gmail.com", full_name: "Wallace Valentim", peso: "104", nascimento: "35", altura: "177", atividade: "Musculação 1:30, 3/4x. Bike e futebol", medicamentos: "Enantato", comorbidades: "Não", objetivo: "Secar tudo", telefone: "" },
  { timestamp: "9/3/2024", email: "nelaine872@gmail.com", full_name: "Elaine Nascimento Rangel", peso: "", nascimento: "", altura: "", atividade: "Parei a academia", medicamentos: "Não", comorbidades: "Bebo coca cola", objetivo: "Secar a barriga", telefone: "" },
  { timestamp: "9/7/2024", email: "vanessavasconceloslopes@gmail.com", full_name: "Vanessa Vasconcelos Lopes", peso: "68", nascimento: "40", altura: "", atividade: "Musculação 1h 3x. Caminhada 30min 3x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Perder celulites nas pernas", telefone: "" },
  { timestamp: "9/8/2024", email: "taina123migucha@gmail.com", full_name: "Thayná silva dos Santos", peso: "147", nascimento: "28", altura: "162", atividade: "Academia de caminhada 1h 5x", medicamentos: "Queratina", comorbidades: "Nao", objetivo: "Qualidade de vida e alcançar objetivo", telefone: "" },
  { timestamp: "9/10/2024", email: "goncalvescunhaclaire@gmail.com", full_name: "Claire Gonçalves Cunha", peso: "79", nascimento: "43", altura: "", atividade: "Não pratica", medicamentos: "Não", comorbidades: "Pressão alta", objetivo: "Perder os kilos", telefone: "" },
  { timestamp: "9/17/2024", email: "carolanny748@gmail.com", full_name: "Anny Caroliny Santiago Amaral", peso: "76", nascimento: "34", altura: "165", atividade: "Musculação 2h 3-4x. Corrida 20min 3-4x", medicamentos: "Creatina, multivitamínico, ômega 3, vitamina C", comorbidades: "Não", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "9/17/2024", email: "crlopes73@gmail.com", full_name: "Carlos Roberto da Silva Lopes", peso: "92", nascimento: "51", altura: "175", atividade: "Musculação 1h 2x. Bicicleta 20min 2x", medicamentos: "Não", comorbidades: "Hipotireoidismo", objetivo: "Peso ideal com massa muscular", telefone: "" },
  { timestamp: "9/17/2024", email: "mb.tavares73@gmail.com", full_name: "Maurício Batista Tavares", peso: "79", nascimento: "48", altura: "", atividade: "Corrida 1h 2-3x por semana", medicamentos: "Termogênico, pré treino, tríbulos, maca peruana, tadalafila 5mg", comorbidades: "Hipotireoidismo", objetivo: "Queimar gordura abdominal e peitoral", telefone: "" },
  { timestamp: "9/20/2024", email: "renatodeazevedosilva2019@gmail.com", full_name: "Renato de Azevedo Silva", peso: "86", nascimento: "42", altura: "", atividade: "Musculação 1:30 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Resultado", telefone: "" },
  { timestamp: "9/20/2024", email: "alemendes5281@hotmail.com", full_name: "Alessandro Gomes Mendes", peso: "", nascimento: "49", altura: "1.76", atividade: "Musculação 1h 3x. Caminhada 30min 3x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecer no mínimo 10 Kg", telefone: "" },
  { timestamp: "9/20/2024", email: "adrianoandrade820@hotmail.com", full_name: "Adriano de Andrade dos Santos", peso: "103", nascimento: "36", altura: "", atividade: "Musculação 1.5h 3x. Caminhada+corrida+bike 2h 1x", medicamentos: "Creatina e pré treino", comorbidades: "Não", objetivo: "Perder barriga e papada", telefone: "" },
  { timestamp: "9/21/2024", email: "galiottojacinta@gemail.com", full_name: "Jacinta Bandeira Galiotto", peso: "", nascimento: "", altura: "1.53", atividade: "Pilates funcional ioga 1h 3x. Bicicleta/caminhada/corrida", medicamentos: "Cálcio e fluoxetina", comorbidades: "Não", objetivo: "Resultado de 14 kilos", telefone: "" },
  { timestamp: "9/22/2024", email: "erikamartins2008@hotmail.com", full_name: "Erika da Silva Martins", peso: "70", nascimento: "42", altura: "1.62", atividade: "Musculação 40min 3x", medicamentos: "Creatina", comorbidades: "Nao", objetivo: "Secar barriga", telefone: "" },
  { timestamp: "9/27/2024", email: "marcelosouto2009@hotmail.com", full_name: "Marcelo gomes de souto", peso: "120", nascimento: "54", altura: "1.8", atividade: "Nada", medicamentos: "Não", comorbidades: "N", objetivo: "Perder 20 kg", telefone: "" },
  { timestamp: "9/30/2024", email: "trapatonni@gmail.com", full_name: "GIovanni Sophia", peso: "133", nascimento: "37", altura: "", atividade: "Musculação 1.5-2h 5x", medicamentos: "Creatina, Whey, Pré-treino, Multivitaminico, Enantato", comorbidades: "Não", objetivo: "Resultado mantendo massa muscular", telefone: "" },
  { timestamp: "10/3/2024", email: "manhaes295@gmail.com", full_name: "Matheus Manhães Azevedo", peso: "59", nascimento: "28", altura: "1.64", atividade: "Academia 1:40h 6 dias", medicamentos: "Durateston 1 ml", comorbidades: "Nao", objetivo: "Ajuda e conhecimento", telefone: "" },
  { timestamp: "10/6/2024", email: "filipe.antune.castro@gmail.com", full_name: "Filipe Antunes de castro", peso: "115", nascimento: "33", altura: "169", atividade: "Musculação 1:30 3-4x. Esteira 30min", medicamentos: "Sibutramina", comorbidades: "Não", objetivo: "Resultado", telefone: "" },
  { timestamp: "10/8/2024", email: "gynleo@gmail.com", full_name: "Leonardo Amaral Costa", peso: "", nascimento: "37", altura: "", atividade: "Musculação 40min 3x", medicamentos: "Durateston", comorbidades: "Restrição a lactose e proteína do leite", objetivo: "Melhorar metabolismo e emagrecer", telefone: "" },
  { timestamp: "10/9/2024", email: "brabopol01@gmail.com", full_name: "Andre Luiz Freitas Gaspar", peso: "123", nascimento: "52", altura: "1.85", atividade: "Caminhada 1h 5x", medicamentos: "Losartana 50mg, hidroclorotiazida 50mg", comorbidades: "Nenhuma", objetivo: "Qualidade de vida", telefone: "" },
  { timestamp: "10/10/2024", email: "fabiokaizer85@gmail.com", full_name: "Fabio kaizer da costa", peso: "104", nascimento: "39", altura: "", atividade: "Futebol 30min 1x. Corrida 30min 1x", medicamentos: "Nao", comorbidades: "Preguiça de fazer exercícios", objetivo: "Perder peso e qualidade de vida", telefone: "" },
  { timestamp: "10/14/2024", email: "jaque_crystal@hotmail.com", full_name: "Jaqueline Silva Melo Braga", peso: "", nascimento: "44", altura: "", atividade: "Caminhada 30min 2x", medicamentos: "Não", comorbidades: "Não", objetivo: "Voltar a ser magra", telefone: "" },
  { timestamp: "10/16/2024", email: "botelhofabiano@gmail.com", full_name: "Fabiano Botelho dos Santos", peso: "", nascimento: "45", altura: "1.8", atividade: "Musculação 1.5h 3-4x. Esteira/transport 20min 2-3x", medicamentos: "Não", comorbidades: "Dores no joelho", objetivo: "Diminuir a região abdominal", telefone: "" },
  { timestamp: "10/16/2024", email: "rodrigosperalta@yahoo.com.br", full_name: "Rodrigo Peralta", peso: "169", nascimento: "44", altura: "173", atividade: "Esteira 1h 1-2x/mês", medicamentos: "Hidroclorotiazida e Captopril (pressão)", comorbidades: "não", objetivo: "Emagrecer e qualidade de vida", telefone: "" },
  { timestamp: "10/16/2024", email: "raphaeldiniz471@gmail.com", full_name: "João Emanuel Nascimento ribeiro diniz", peso: "87", nascimento: "", altura: "1.77", atividade: "Musculação 1.5h 6x", medicamentos: "Whey protein, hipercalórico, creatina", comorbidades: "Não tenho", objetivo: "...", telefone: "" },
  { timestamp: "10/17/2024", email: "gabi.coutinho31@gmail.com", full_name: "Gabriela Coutinho", peso: "69", nascimento: "41", altura: "1.49", atividade: "Nenhum", medicamentos: "Fisiogem ferro forte e mecoby", comorbidades: "Anemia", objetivo: "Reeducação alimentar e emagrecimento", telefone: "" },
  { timestamp: "10/19/2024", email: "crisasimoes@icloud.com", full_name: "Cristiane Almeida Simões", peso: "86", nascimento: "39", altura: "", atividade: "Musculação 40min intenso 5x", medicamentos: "Nao", comorbidades: "Nao", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "10/19/2024", email: "admsimone2011@gmail.com", full_name: "Simone Maria Ferreira", peso: "70", nascimento: "46", altura: "150", atividade: "Muay thai 1h 3x. Caminhada 45min 5x", medicamentos: "Whey e creatina", comorbidades: "Não", objetivo: "Ter resultado", telefone: "" },
  { timestamp: "10/19/2024", email: "rhalanes@gmail.com", full_name: "Rhayssa Lanes Gonçalves", peso: "", nascimento: "37", altura: "", atividade: "Musculação 4x 1h. Aeróbicos 6x 40min", medicamentos: "Creatina, Whey", comorbidades: "Enxaqueca", objetivo: "Definição e massa muscular", telefone: "" },
  { timestamp: "10/21/2024", email: "thalitalopesnunes2@gmail.com", full_name: "Thalita Lopes Nunes Marques", peso: "78", nascimento: "41", altura: "168", atividade: "Caminhada 1h 3x", medicamentos: "Velija, rexult, alprazolan", comorbidades: "Fibromialgia", objetivo: "Rapidez de resultado", telefone: "" },
  { timestamp: "10/23/2024", email: "lukass.amorimqi@gmail.com", full_name: "lucas amorim da cunha", peso: "80", nascimento: "27", altura: "", atividade: "Musculação 30-40min 5x", medicamentos: "Enantato 1ml seg e qui", comorbidades: "não", objetivo: "Shape de praia", telefone: "" },
  { timestamp: "10/24/2024", email: "jairoludovico100843@gmail.com", full_name: "Jairo de Azevedo Ludovico", peso: "92", nascimento: "44", altura: "171", atividade: "Musculação 1h 3x (parado 3 meses). Corrida 30min 3x", medicamentos: "Creatina, whey, omega 3", comorbidades: "Nao", objetivo: "Secar tudo", telefone: "" },
  { timestamp: "10/26/2024", email: "fellipedecastrosantos@gmail.com", full_name: "Fellipe de Castro Santos", peso: "", nascimento: "37", altura: "", atividade: "Musculação, Muay Thai, Capoeira, Bike, Caminhada 7 dias", medicamentos: "Whey Protein, Maca Peruana, Tribulus, Ioimbina", comorbidades: "Nao", objetivo: "Ficar magro", telefone: "" },
  { timestamp: "10/29/2024", email: "heenamenezes2008@hotmail.com", full_name: "Maria Helena da Silva Menezes", peso: "", nascimento: "", altura: "", atividade: "Musculação 1:40h 5x. Corrida 45min 3x", medicamentos: "Creatina, Whey", comorbidades: "1 hérnia disco, ciático desgastado", objetivo: "Baixar colesterol", telefone: "" },
  { timestamp: "11/1/2024", email: "luizeduardodias270@gmail.com", full_name: "Luiz Eduardo Ferreira dias da Conceição", peso: "88", nascimento: "17", altura: "", atividade: "Musculação e Muay thai 1-2:30h 6x", medicamentos: "Não", comorbidades: "Não", objetivo: "...", telefone: "" },
  { timestamp: "11/2/2024", email: "viviane10le@yahoo.com.br", full_name: "Viviane Souza", peso: "67", nascimento: "40", altura: "165", atividade: "Não", medicamentos: "Não", comorbidades: "Não", objetivo: "Auto estima, qualidade de vida", telefone: "" },
  { timestamp: "11/6/2024", email: "filhow@gmail.com", full_name: "José Viana", peso: "", nascimento: "43", altura: "", atividade: "Musculação e ergometria 1.5h 5x. Caminhada 30min 4x", medicamentos: "Não", comorbidades: "Pressão alta", objetivo: "Metabolizar 30 kg", telefone: "" },
  { timestamp: "11/9/2024", email: "Brussier_2@hotmail.com", full_name: "Robert Brussier da Silva", peso: "96", nascimento: "35", altura: "", atividade: "Musculação 2h 5x. Cardio 40-1h 2x", medicamentos: "Enantato", comorbidades: "Não", objetivo: "Massa e definição", telefone: "" },
  { timestamp: "11/18/2024", email: "pauloopentk@gmail.com", full_name: "Paulo Amaro de Abreu", peso: "82", nascimento: "37", altura: "", atividade: "Musculação 1h 5x", medicamentos: "Durateston", comorbidades: "Não", objetivo: "Ganhar peso massa", telefone: "" },
  { timestamp: "11/19/2024", email: "marketingnatumix@gmail.com", full_name: "Lilian Rosa de Cunto", peso: "86", nascimento: "29", altura: "158", atividade: "Crossfit 60min 3x", medicamentos: "Não mais aceitaria usar", comorbidades: "Nenhuma", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "11/20/2024", email: "juliane_rms@hotmail.com", full_name: "Juliane Rodrigues Menezes Silva", peso: "", nascimento: "37", altura: "160", atividade: "Crossfit 1h 5x. Bicicleta/caminhada 1h 2x", medicamentos: "Não", comorbidades: "Não", objetivo: "Perder 5kg", telefone: "" },
  { timestamp: "11/27/2024", email: "lilianerody@gmail.com", full_name: "Liliane Rody", peso: "92", nascimento: "43", altura: "", atividade: "Não", medicamentos: "Não", comorbidades: "Não", objetivo: "Ter resultados", telefone: "" },
  { timestamp: "11/28/2024", email: "evertonfranciscosilva@gmail.com", full_name: "Everton da Silva Francisco", peso: "", nascimento: "51", altura: "1.83", atividade: "Musculação 1:30-2h 2-3x", medicamentos: "Não", comorbidades: "Hérnia de disco L4 L5", objetivo: "Perder barriga e corpo muscular", telefone: "" },
  { timestamp: "11/28/2024", email: "junior.carvalho01@hotmail.com", full_name: "alexandre salviano de carvalho junior", peso: "112", nascimento: "32", altura: "182", atividade: "Musculação 50min 3-4x. Corrida 40min 2x", medicamentos: "Sibutramina e enantato", comorbidades: "não", objetivo: "Perder 12kg", telefone: "" },
  { timestamp: "11/28/2024", email: "oliveirasantostj26@gmail.com", full_name: "Edson Oliveira dos Santos", peso: "", nascimento: "30", altura: "177", atividade: "Musculação 1h 5x. Ciclismo 2h fins de semana", medicamentos: "Enantato e Deca", comorbidades: "Não", objetivo: "Definido com aparência grande", telefone: "" },
  { timestamp: "11/29/2024", email: "carolmenddes@gmail.com", full_name: "Carolina Mendes Marins", peso: "", nascimento: "34", altura: "", atividade: "Musculação e Esteira 1:30 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecimento e condicionamento físico", telefone: "" },
  { timestamp: "12/10/2024", email: "ludmillaalbuquerque7220@gmail.com", full_name: "Ludmilla Rocha", peso: "75", nascimento: "40", altura: "", atividade: "2h incluindo cardio 5x", medicamentos: "Puran t4 150mg", comorbidades: "Nao", objetivo: "Qualidade de vida", telefone: "" },
  { timestamp: "12/10/2024", email: "matheusrisaffe11@icloud.com", full_name: "Matheus Risaffe", peso: "", nascimento: "", altura: "175", atividade: "Musculação 1-1:20h 6x. Esteira 30min", medicamentos: "Durateston, deca, masterom, hemogenin", comorbidades: "Não", objetivo: "Acompanhamento", telefone: "" },
  { timestamp: "12/17/2024", email: "mylenna_andrade@hotmail.com", full_name: "Mylenna Andrade de Anchieta", peso: "", nascimento: "27", altura: "", atividade: "Musculação 1:30h 6-7x. Caminhada/bike 20-30min 3x", medicamentos: "Creatina e whey", comorbidades: "Não", objetivo: "Resultados positivos esteticamente", telefone: "" },
  { timestamp: "12/17/2024", email: "daniellevalerio3@gmail.com", full_name: "Danielle Valério Marouço", peso: "79", nascimento: "43", altura: "", atividade: "Musculação 3h 3-4x. Caminhada na praia", medicamentos: "Testosterona", comorbidades: "Sim", objetivo: "Definir", telefone: "" },
  { timestamp: "12/18/2024", email: "matheusaraujo18bh@gmail.com", full_name: "Matheus Henrique Araújo", peso: "96", nascimento: "26", altura: "1.78", atividade: "Musculação 2h+ 5x. Esteira 30-40min", medicamentos: "Sim", comorbidades: "Não", objetivo: "Conquistar o shape", telefone: "" },
  { timestamp: "12/19/2024", email: "sousaednea@gmail.com", full_name: "Ednea sousa dos Santos", peso: "", nascimento: "43", altura: "162", atividade: "Musculação e caminhada 1h 1x", medicamentos: "Testosterona e progesterona", comorbidades: "Nao", objetivo: "Perder 12kg", telefone: "" },
  { timestamp: "12/19/2024", email: "renatojpm5231@gmail.com", full_name: "Renato Luiz Moreira", peso: "70", nascimento: "52", altura: "", atividade: "Flexões, abdominais, levantamento 1h 4x", medicamentos: "Não", comorbidades: "Não", objetivo: "Resultados", telefone: "" },
  { timestamp: "12/20/2024", email: "pagliasse107@gmail.com", full_name: "Gabriel Cardoso Pagliasse", peso: "81", nascimento: "30", altura: "", atividade: "Todos 2h 6x. Corrida 1h 3x", medicamentos: "Dura", comorbidades: "Nao", objetivo: "Engordar", telefone: "" },
  { timestamp: "12/30/2024", email: "lisleidenoma2@gmail.com", full_name: "Lislei Cristine santos farias", peso: "55", nascimento: "40", altura: "", atividade: "Musculação 2h 3x. Corrida 20-30min 3x", medicamentos: "Oxandrolona com masteron", comorbidades: "Não", objetivo: "Sim", telefone: "" },
  { timestamp: "1/1/2025", email: "alepeze@gmail.com", full_name: "Alexandre Silva Pezenato", peso: "85", nascimento: "50", altura: "", atividade: "Futebol e hidroginástica 2x 45min. Caminhada 1h 3x", medicamentos: "Vitamina", comorbidades: "Diabetes", objetivo: "Massa muscular", telefone: "" },
  { timestamp: "1/1/2025", email: "ledacristinamello@gmail.com", full_name: "Leda Cristina dos Santos Melo pezenato", peso: "81", nascimento: "39", altura: "159", atividade: "Musculação 1h 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Melhorar o corpo", telefone: "21988597188" },
  { timestamp: "1/7/2025", email: "tiagowillow@gmail.com", full_name: "Tiago Ramos Teixeira", peso: "85", nascimento: "40", altura: "175", atividade: "Musculação 1h 3x. Esteira 10min 3x", medicamentos: "Não", comorbidades: "Não", objetivo: "Chegar ao objetivo", telefone: "" },
  { timestamp: "1/7/2025", email: "camiladasilva748@gmail.com", full_name: "Camila Giulianna da Silva", peso: "", nascimento: "36", altura: "157", atividade: "Musculação 1h 3x. Cardio 1:30 6x", medicamentos: "Creatina, psyllium, garcinia, zinco, magnésio, vitamina D", comorbidades: "Não", objetivo: "Perder 12kg", telefone: "" },
  { timestamp: "1/8/2025", email: "andersonrosa2004@gmail.com", full_name: "Cipriano Anderson", peso: "82", nascimento: "39", altura: "", atividade: "Musculação 1-1.5h 5x. Cardio domingo 40-60min", medicamentos: "Ioimbina e creatina", comorbidades: "Nenhuma", objetivo: "Ganho de força e definição", telefone: "" },
  { timestamp: "1/8/2025", email: "adrielinunes13@gmail.com", full_name: "Adrieli de Albuquerque Nunes Silva", peso: "127.2", nascimento: "24", altura: "173", atividade: "Musculação 1:30-2h 5-6x. Caminhada/bike/transport 30-40min 5-6x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecimento e definição", telefone: "21988401238" },
  { timestamp: "1/8/2025", email: "alvescarlosdavi4@gmail.com", full_name: "Carlos Alberto da Costa Alves", peso: "", nascimento: "", altura: "", atividade: "Não", medicamentos: "Não", comorbidades: "Obesidade", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "1/8/2025", email: "miretisilva@gmail.com", full_name: "Mireti Souza", peso: "73", nascimento: "31", altura: "169", atividade: "Não", medicamentos: "Não", comorbidades: "Não", objetivo: "Adaptar à rotina", telefone: "21964116649" },
  { timestamp: "1/9/2025", email: "matheustvrs@gmail.com", full_name: "Matheus Henrique Gonçalves Tavares", peso: "", nascimento: "29", altura: "", atividade: "Musculação 1h 5x", medicamentos: "Nenhum", comorbidades: "Nenhuma", objetivo: "Conhecimento e auxílio especializado", telefone: "62981269286" },
  { timestamp: "1/13/2025", email: "fabiofdacosta@gmail.com", full_name: "Fábio Fernandes da Costa", peso: "110", nascimento: "45", altura: "180", atividade: "Vou me matricular", medicamentos: "Não", comorbidades: "Não", objetivo: "...", telefone: "21995553649" },
  { timestamp: "1/15/2025", email: "vitor.t.mello@gmail.com", full_name: "VITOR HUGO TRAJANO DE MELLO", peso: "", nascimento: "36", altura: "183", atividade: "Musculação 1:30 5-6x. Corrida 20min 5-6x", medicamentos: "Creatina, Whey, Durateston, Stanazolol", comorbidades: "Não", objetivo: "Hipertrofia e perder gordura", telefone: "21974373884" },
  { timestamp: "1/17/2025", email: "thais.lima163@gmail.com", full_name: "Thaís lima do Amaral barbosa", peso: "", nascimento: "29", altura: "", atividade: "Musculação 1h 3x. Caminhada/bike 1h 2x", medicamentos: "Não", comorbidades: "Intolerante a lactose", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "1/20/2025", email: "priscilaribeiro826@gmail.com", full_name: "Priscila de Jesus Ribeiro", peso: "90", nascimento: "41", altura: "1.72", atividade: "Musculação 2h 5x. Esteira/bike/escada 30min 2x", medicamentos: "Fitoterápicos, maca peruana, tribulus, spirulina, clorela, whey", comorbidades: "Não", objetivo: "Objetivo necessário", telefone: "34999772292" },
  { timestamp: "1/22/2025", email: "simonteaz@gmail.com", full_name: "Simone Monteiro de Azevedo", peso: "", nascimento: "43", altura: "", atividade: "Não", medicamentos: "Anticoncepcional (microvlar)", comorbidades: "Bucite e tendinite joelho e ombro", objetivo: "Emagrecer", telefone: "" },
  { timestamp: "1/23/2025", email: "augustoprofissionaldireito@gmail.com", full_name: "Augusto Amorim", peso: "", nascimento: "21", altura: "", atividade: "Musculação 1:30-2h 5-6x. Esteira 30min 5x", medicamentos: "Testosterona, deca, masteron", comorbidades: "Não", objetivo: "Hipertrofia", telefone: "" },
  { timestamp: "1/23/2025", email: "Xandaospub@gmail.com", full_name: "Alexander Dutra", peso: "98", nascimento: "50", altura: "", atividade: "Musculação 1:10h 3x. Bicicleta 1h 3x", medicamentos: "Deca e testosterona", comorbidades: "Barriga", objetivo: "Definir o corpo", telefone: "" },
  { timestamp: "1/23/2025", email: "amandazampieri12@gmail.com", full_name: "AMANDA GIROTO FERREIRA", peso: "64.8", nascimento: "", altura: "1.7", atividade: "Musculação 1h 5x. Esteira 15-20min 5x", medicamentos: "Vitaminas e ansiolíticos (bariatrica)", comorbidades: "Insônia", objetivo: "Músculos e definição", telefone: "" },
  { timestamp: "1/23/2025", email: "davilasilva9@gmail.com", full_name: "Andreza Dávila Bilela da Silva", peso: "69", nascimento: "31", altura: "", atividade: "Musculação 3-4x. Bicicleta 30min diário", medicamentos: "Suplementos", comorbidades: "Não", objetivo: "Chegar aos objetivos", telefone: "87981603261" },
  { timestamp: "1/26/2025", email: "andressadossantosreis@gmail.com", full_name: "Andressa dos Santos Reis", peso: "70", nascimento: "33", altura: "176", atividade: "Natação e musculação 1h cada. Esteira/bike 20min 3x", medicamentos: "Whey protein", comorbidades: "Não", objetivo: "Perder gordura e definição", telefone: "21983473764" },
  { timestamp: "1/31/2025", email: "gilmardigito1@gmail.com", full_name: "Gilmar de Andrade do Vale", peso: "75", nascimento: "39", altura: "166", atividade: "Musculação 3+ anos 5x", medicamentos: "Creatina, whey, omega 3", comorbidades: "Toxoplasmose ocular", objetivo: "Resultado positivo rápido", telefone: "21999047148" },
  { timestamp: "1/31/2025", email: "raphael.limarodrigues@gmail.com", full_name: "RAPHAEL DE LIMA RODRIGUES", peso: "", nascimento: "40", altura: "1.69", atividade: "Musculação 1h 6x. Aerolítico 30min 3x", medicamentos: "Omega 3, coenzima Q10, creatina, whey", comorbidades: "Não", objetivo: "Perda de peso", telefone: "21996636658" },
  { timestamp: "1/31/2025", email: "kellyccb_@hotmail.com", full_name: "Kelly Cristina Barbosa da Silva", peso: "", nascimento: "", altura: "", atividade: "Musculação 1h 5x (retornou após 10 meses)", medicamentos: "Whey e creatina", comorbidades: "Dor no joelho direito", objetivo: "Perder gordura", telefone: "21988272444" },
  { timestamp: "2/1/2025", email: "samuelvallenca@gmail.com", full_name: "Samuel vallenca", peso: "74", nascimento: "45", altura: "176", atividade: "Musculação 1:30 6x. Corrida 30min 5x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Massa muscular e definição", telefone: "" },
  { timestamp: "2/5/2025", email: "defk.negocios@gmail.com", full_name: "Fábio Galdino Jardim", peso: "64.7", nascimento: "43", altura: "1.75", atividade: "Musculação 5x", medicamentos: "Magnésio, zinco, zma, creatina, whey", comorbidades: "Dor na coluna", objetivo: "Corpo definido com volume", telefone: "21964931729" },
  { timestamp: "2/5/2025", email: "deccachearthur@gmail.com", full_name: "Paula Cristina Deccache da cruz", peso: "65", nascimento: "39", altura: "165", atividade: "Musculação 1:30h 4x. Caminhada 30min 2x", medicamentos: "Masteron", comorbidades: "Não", objetivo: "Organizar alimentação", telefone: "21970150704" },
  { timestamp: "2/5/2025", email: "slucas994@yahoo.com.br", full_name: "Lucas dos santos souza", peso: "82.5", nascimento: "36", altura: "168", atividade: "Musculação 1:30 5x. Corrida 20min 5x", medicamentos: "Creatina", comorbidades: "Não", objetivo: "Shape legal", telefone: "21996266230" },
  { timestamp: "2/6/2025", email: "carloswaltrich@hotmail.com", full_name: "Carlos waltrich", peso: "92", nascimento: "30", altura: "192", atividade: "Musculação 1:30 5x. Esteira 15min 5x", medicamentos: "Enantato testo", comorbidades: "Nao", objetivo: "Aumento de massa e baixo bf", telefone: "" },
  { timestamp: "2/8/2025", email: "vagnerheiderscheidt2@gmail.com", full_name: "Vagner Heiderscheidt", peso: "80", nascimento: "25", altura: "173", atividade: "Musculação 50-60min 5x. Caminhada 1h 6x", medicamentos: "Whey, Vitamina D, C, Complexo B, Melatonina", comorbidades: "Não", objetivo: "Resultados", telefone: "48991412961" },
  { timestamp: "2/9/2025", email: "isisclemente10@gmail.com", full_name: "Isis de Oliveira Clemente", peso: "88", nascimento: "28", altura: "", atividade: "Musculação futvôlei 1h. Caminhada 40min 3x", medicamentos: "Quetiapina, lítio, clonazepam", comorbidades: "TAB TIPO 1", objetivo: "Chegar na meta", telefone: "31988326130" },
  { timestamp: "2/10/2025", email: "humbertocarvalho1989@gmail.com", full_name: "HUMBERTO Fernando pinto Carvalho", peso: "75", nascimento: "35", altura: "", atividade: "Musculação 5x", medicamentos: "BCAA e creatina", comorbidades: "Não", objetivo: "CRESCER", telefone: "" },
  { timestamp: "2/13/2025", email: "carlos_viniciusmartins@hotmail.com", full_name: "CARLOS VINICIUS DA SILVA MARTINS", peso: "", nascimento: "", altura: "", atividade: "Vou iniciar", medicamentos: "Vou iniciar Durateston e Deca", comorbidades: "Não", objetivo: "Massa muscular e definição", telefone: "11986209861" },
  { timestamp: "2/13/2025", email: "cristianoliveiramon@gmail.com", full_name: "Cristian oliveira mondin", peso: "102", nascimento: "25", altura: "178", atividade: "1h cardio jejum + musculação noite. ABC 7x", medicamentos: "Enantato, vitamina C, omega 3", comorbidades: "Asma", objetivo: "Secar e depois bulking", telefone: "51982928051" },
  { timestamp: "2/14/2025", email: "celli_lima@yahoo.com.br", full_name: "Marcelli de Lima Pereira", peso: "80", nascimento: "37", altura: "", atividade: "Musculação 1:30 4x. Esteira/escada 40min 4x", medicamentos: "Propranolol", comorbidades: "Enxaqueca", objetivo: "Suporte", telefone: "21995668497" },
  { timestamp: "2/15/2025", email: "escritoriovisioanrio@gmail.com", full_name: "Guilherme de Lima saiol soares", peso: "88", nascimento: "32", altura: "186", atividade: "Musculação 1h 4-5x. Esteira/corrida 25min 3x", medicamentos: "Ainda não", comorbidades: "Nao", objetivo: "Melhorar disposição", telefone: "21965963896" },
  { timestamp: "2/17/2025", email: "guimaraes.info@gmail.com", full_name: "RAFAEL GUIMARAES DA ROSA", peso: "", nascimento: "35", altura: "", atividade: "Musculação 1:30 4x. Caminhada 20min 2x", medicamentos: "Durateston, creatina, pré treino", comorbidades: "Não", objetivo: "Emagrecimento e massa magra", telefone: "21964096653" },
  { timestamp: "2/18/2025", email: "julia.belisario@hotmail.com", full_name: "Julia Belisario", peso: "", nascimento: "31", altura: "164", atividade: "Musculação+funcional areia 1h 3x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecer/perder barriga", telefone: "21998816236" },
  { timestamp: "2/24/2025", email: "thiagoferreiradsa@gmail.com", full_name: "Thiago Araujo", peso: "", nascimento: "", altura: "", atividade: "Musculação 1:30h 5-6x. Corrida 30-50min 2x", medicamentos: "Creatina, Durateston", comorbidades: "Não", objetivo: "Aumentar condição física", telefone: "21970001741" },
  { timestamp: "2/25/2025", email: "william425@outlook.com", full_name: "William Silva de Sousa", peso: "", nascimento: "", altura: "1.7", atividade: "Musculação 1h 4-5x. Caminhada 30min 2x", medicamentos: "Não", comorbidades: "Nenhuma", objetivo: "Bons resultados", telefone: "22999564783" },
  { timestamp: "2/27/2025", email: "hugocarneiro.x@gmail.com", full_name: "Hugo Xavier Carneiro", peso: "84", nascimento: "42", altura: "", atividade: "Musculação 1:30 4-5x. Bike/corrida 30min 2-3x", medicamentos: "Enantato e masteron", comorbidades: "Não", objetivo: "Acompanhamento atividades e reposição hormonal", telefone: "21964686761" },
  { timestamp: "2/28/2025", email: "silviojunior.napiwoski@gmail.com", full_name: "Silvio Junior Napiwoski", peso: "101", nascimento: "33", altura: "172", atividade: "Musculação 1:30 + jiu-jitsu 2h", medicamentos: "Durateston", comorbidades: "Não", objetivo: "Alimentar e hormonal otimizar ganhos", telefone: "" },
  { timestamp: "2/28/2025", email: "andrevictor211210@gmail.com", full_name: "André Victor da Costa Machado", peso: "82", nascimento: "27", altura: "", atividade: "Musculação 1:30 5-6x. Jiu-jitsu 1h 2x", medicamentos: "Enantato, trembo, vit D, B12, omega 3, whey, albumina", comorbidades: "Nenhuma", objetivo: "Melhorar físico e saúde", telefone: "48999628888" },
  { timestamp: "3/2/2025", email: "fernanda90fenix@gmail.com", full_name: "Aline Lucas de Carvalho", peso: "90", nascimento: "43", altura: "", atividade: "Pilates 40min 2x. Musculação 2h 4x. Transport 40min 4x", medicamentos: "Creatina, pré-treino, whey. Carbolitium", comorbidades: "Transtorno bipolar", objetivo: "Chegar e manter objetivos", telefone: "21999016457" },
  { timestamp: "3/6/2025", email: "daniellerosa103@gmail.com", full_name: "Daniele Rodrigues Nascimento", peso: "", nascimento: "26", altura: "", atividade: "Musculação 2:30 5x. Caminhada 4h", medicamentos: "B12, omega 3, sibutramina, oristat, escitalopram", comorbidades: "Não", objetivo: "Melhorar físico", telefone: "31984731030" },
  { timestamp: "3/7/2025", email: "daniellegil81@gmail.com", full_name: "Danielle M Gil", peso: "73", nascimento: "43", altura: "", atividade: "Musculação 2h 4-5x. Bicicleta/escada diário 30min", medicamentos: "Whey, creatina, deca", comorbidades: "Não", objetivo: "Ganho de massa", telefone: "21970140401" },
  { timestamp: "3/10/2025", email: "ale_rj.lima@hotmail.com", full_name: "Alessandra Lima", peso: "86", nascimento: "37", altura: "165", atividade: "Crossfit 1h 3x", medicamentos: "Puran t4", comorbidades: "Nao", objetivo: "Emagrecer", telefone: "21999713031" },
  { timestamp: "3/10/2025", email: "matheussantiago2025@hotmail.com", full_name: "Matheus Santiago Oliveira", peso: "87", nascimento: "29", altura: "1.75", atividade: "Musculação 1:30 6x. Caminhada/corrida 30min 5x", medicamentos: "Enantato", comorbidades: "Retirada de vesícula", objetivo: "Melhorar físico", telefone: "82991121045" },
  { timestamp: "3/11/2025", email: "supergagaroto@gmail.coms", full_name: "MICHAEL DOUGLAS DE SOUZA OLIVEIRA", peso: "69", nascimento: "20", altura: "", atividade: "Musculação 2h 5x. Caminhada 1h 5x", medicamentos: "En", comorbidades: "Não", objetivo: "O básico", telefone: "" },
  { timestamp: "3/12/2025", email: "carolinyamaral@hotmail.com", full_name: "Anny Caroliny Santiago Amaral", peso: "72", nascimento: "34", altura: "165", atividade: "Musculação 2h 3-4x. Corrida 20-30min 3-4x", medicamentos: "Creatina, glutamina, ômega 3, vitamina C, multivitamínico", comorbidades: "Não", objetivo: "Alcançar objetivo", telefone: "21974160137" },
  { timestamp: "3/12/2025", email: "davi7william@gmail.com", full_name: "DAVI WILLIAM BERNARDO", peso: "160", nascimento: "27", altura: "", atividade: "Musculação 1h 6x. Hidro fitness 50min 6x", medicamentos: "Creatina, vitamina D, B12", comorbidades: "Não", objetivo: "Ajuda com treino, dieta e hormônios", telefone: "44988180649" },
  { timestamp: "3/13/2025", email: "loma.amaral@gmail.com", full_name: "PALOMA MARQUES AMARAL", peso: "", nascimento: "", altura: "", atividade: "Musculação 7x. Corrida 40-60min 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Perder gordura, hipertrofia", telefone: "21976820722" },
  { timestamp: "3/14/2025", email: "gcozendeyb@gmail.com", full_name: "Glaucia Cozendey Barreto", peso: "88", nascimento: "43", altura: "", atividade: "Musculação/Spinning 1h 5x", medicamentos: "Creatina e Whey", comorbidades: "Não", objetivo: "Emagrecimento e muscular", telefone: "21983692410" },
  { timestamp: "3/19/2025", email: "fga.edson@gmail.com", full_name: "Edson Oliveira dos Santos", peso: "", nascimento: "31", altura: "177", atividade: "Musculação 1h 4-5x. Esteira 30-50min 4x", medicamentos: "Fazia", comorbidades: "Não", objetivo: "Resultados", telefone: "82988091883" },
  { timestamp: "3/19/2025", email: "esthefani.sabino92@gmail.com", full_name: "Esthefani Aparecida Sabino Ribeiro", peso: "82", nascimento: "33", altura: "176", atividade: "Musculação 1:30 5x. Caminhada/bike/escada 30min 3x", medicamentos: "Venlafaxina, Topiramato, Masteron", comorbidades: "TAG e depressão", objetivo: "Emagrecimento e definição", telefone: "11953354249" },
  { timestamp: "3/23/2025", email: "gabejjgamepass@gmail.com", full_name: "Gabriel amador ferreira", peso: "88", nascimento: "25", altura: "169", atividade: "Musculação 1h 5x", medicamentos: "Clomid", comorbidades: "Não entendi", objetivo: "Emagrecer", telefone: "51996428922" },
  { timestamp: "3/24/2025", email: "ricardomaia.kiko@gmail.com", full_name: "Ricardo de Souza Maia", peso: "106", nascimento: "50", altura: "1.79", atividade: "Musculação 2h 5-6x. Caminhada/corrida 30-40min 5x", medicamentos: "Pressat 5mg, dura, Deca", comorbidades: "Não", objetivo: "Peso desejado com qualidade e saúde", telefone: "21979159623" },
  { timestamp: "3/24/2025", email: "andrezamesquitalash@gmail.com", full_name: "Maria Andreza Mesquita do Nascimento", peso: "65", nascimento: "30", altura: "1.62", atividade: "Musculação 1:30-2h 5x. Caminhada 20min 2x", medicamentos: "Whey, creatina", comorbidades: "...", objetivo: "Massa muscular e definição", telefone: "21988298490" },
  { timestamp: "3/27/2025", email: "cecilia.star18@gmail.com", full_name: "Cecília Star Maia Cunha", peso: "66", nascimento: "38", altura: "160", atividade: "Musculação 1:30 6x", medicamentos: "Durateston, Masteron, oxandrolona", comorbidades: "Não", objetivo: "Baixar BF e massa magra", telefone: "21994742967" },
  { timestamp: "3/27/2025", email: "mariosergiomoreira23@gmail.com", full_name: "Mario Sérgio da Silva Moreira", peso: "80", nascimento: "39", altura: "", atividade: "Musculação 2h 4-5x. Corrida 20min 3x", medicamentos: "Suplementos", comorbidades: "Nao", objetivo: "Resultado", telefone: "21976503395" },
  { timestamp: "3/28/2025", email: "michellyfariasster@gmail.com", full_name: "Michelly dos santos farias", peso: "", nascimento: "46", altura: "", atividade: "Jiu Jitsu, musculação e canoa 1-2h 5x", medicamentos: "Tapazol 10mg, sertalina 50mg", comorbidades: "Nao", objetivo: "Mudar minha vida", telefone: "21998953492" },
  { timestamp: "3/28/2025", email: "evertonl1985@hotmail.com", full_name: "Everton Luiz de Araújo Souza", peso: "88", nascimento: "39", altura: "", atividade: "Ciclismo, corrida 1h 3-4x", medicamentos: "Não", comorbidades: "Nao", objetivo: "Emagrecimento, definição e massa", telefone: "21996581178" },
  { timestamp: "3/28/2025", email: "nascimentosilvathiago@gmail.com", full_name: "Thiago Silva do Nascimento", peso: "", nascimento: "43", altura: "173", atividade: "Musculação 1h 2x", medicamentos: "Creatina, ômega 3, vitaminas", comorbidades: "Não", objetivo: "Perder 5kg e ganhar massa", telefone: "21964264779" },
  { timestamp: "3/30/2025", email: "avcs2605@gmail.com", full_name: "Adriana Viana chaves", peso: "81.8", nascimento: "55", altura: "", atividade: "Musculação 2h 5x. Bicicleta 20-30min 3x", medicamentos: "Masteron", comorbidades: "Não tenho", objetivo: "Perder gordura", telefone: "21975111644" },
  { timestamp: "3/31/2025", email: "werickbrayon2@gmail.com", full_name: "werick brayon", peso: "73", nascimento: "23", altura: "165", atividade: "Musculação 2h 5x. Cardio no parque 1h 5x", medicamentos: "Pantoprazol, enantato 250mg", comorbidades: "não", objetivo: "Aprender e evoluir", telefone: "98999688393" },
  { timestamp: "4/1/2025", email: "willgonsilva@gmail.com", full_name: "WILLIAM GONCALVES DA SILVA", peso: "108", nascimento: "54", altura: "", atividade: "NÃO", medicamentos: "Não", comorbidades: "Diabete", objetivo: "Perda de peso", telefone: "" },
  { timestamp: "4/1/2025", email: "det100mais@gmail.com", full_name: "Espedito Stanley Marques Brandão", peso: "", nascimento: "25", altura: "", atividade: "Musculação 40-60min 6x. Caminhada/bike 20-30min 3-5x", medicamentos: "Venvanse, Sertralina 100mg, Enantato 250mg", comorbidades: "Obesidade", objetivo: "Mudar meu físico", telefone: "86981210794" },
  { timestamp: "4/2/2025", email: "erika-duda@outlook.come", full_name: "ERIKA FERREIRA GONCALVES", peso: "60", nascimento: "30", altura: "157", atividade: "Musculação 1h 3x. Caminhada/bike 20min 2x", medicamentos: "Nao", comorbidades: "Não", objetivo: "Resultado", telefone: "" },
  { timestamp: "4/2/2025", email: "cristiane.estevo@hotmail.com.br", full_name: "Cristiane da Silva Estevo Vaz", peso: "83", nascimento: "36", altura: "172", atividade: "Musculação e Crossfit 2:30 5x. Corrida 30min 4x", medicamentos: "Ox", comorbidades: "Não", objetivo: "Hipertrofia e emagrecimento", telefone: "21998545931" },
  { timestamp: "4/4/2025", email: "generoso002@gmail.com", full_name: "BRUNO MONTEIRO GENEROSO", peso: "107", nascimento: "44", altura: "", atividade: "Funcional 1h 5x", medicamentos: "Enantato 250mg, Whey, Quelaplus", comorbidades: "Hipertensão", objetivo: "Volume", telefone: "21994392449" },
  { timestamp: "4/4/2025", email: "edsonjrvieira2004@gmail.com", full_name: "édson espíndola vieira", peso: "", nascimento: "20", altura: "", atividade: "Musculação 1:30h 6x. Natação/corrida", medicamentos: "Creatina", comorbidades: "nenhuma", objetivo: "Secar e ganhar massa", telefone: "" },
  { timestamp: "4/5/2025", email: "christian.casali@yahoo.com.br", full_name: "CHRISTIAN CASALI MACHADO", peso: "82", nascimento: "37", altura: "1.77", atividade: "Musculação 2h 3x. Cardio 30-60min", medicamentos: "Sim", comorbidades: "Não", objetivo: "Condicionamento e recuperação joelho", telefone: "21969597574" },
  { timestamp: "4/5/2025", email: "Look.video.v@gmail.com", full_name: "Julio cezar de sousa barbosa", peso: "", nascimento: "48", altura: "", atividade: "Musculação 1:30 4x. Esteira 30min 2x", medicamentos: "Dura", comorbidades: "Não", objetivo: "Emagrecer e definir", telefone: "" },
  { timestamp: "4/7/2025", email: "nalvaeudora@gmail.com", full_name: "ELINALVA BEZERRA DE OLIVEIRA", peso: "85", nascimento: "40", altura: "", atividade: "Musculação 1:30-2h 5x. Bike/escada/esteira 30min 4-5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Ajudar no objetivo", telefone: "21973456068" },
  { timestamp: "4/8/2025", email: "andersoncaldeira01@gmail.com", full_name: "ANDERSON CALDEIRA DO ESPIRITO SANTO", peso: "", nascimento: "42", altura: "1.84", atividade: "Musculação 40min 2x. Caminhada 20min 2x", medicamentos: "Durateston", comorbidades: "Não", objetivo: "Emagrecer", telefone: "21964772417" },
  { timestamp: "4/9/2025", email: "michellemmota.mmm@gmaiil.com", full_name: "MICHELLE MELLO MOTA", peso: "", nascimento: "46", altura: "", atividade: "Musculação, Crossfit, Muay Thai, Jiu-jitsu", medicamentos: "Sim", comorbidades: "Não", objetivo: "Perda de gordura, hipertrofia", telefone: "21964628065" },
  { timestamp: "4/11/2025", email: "taynaralemos.alves@gmail.com", full_name: "Taynara Lemos Santana", peso: "90", nascimento: "30", altura: "1.7", atividade: "Musculação 2h 4x. Corrida 30min 4x", medicamentos: "Nada", comorbidades: "Nao", objetivo: "Emagrecer", telefone: "21964130770" },
  { timestamp: "4/11/2025", email: "fernandopalmeira2901@gmail.com", full_name: "Fernando Paineira Pereira", peso: "90", nascimento: "38", altura: "173", atividade: "Musculação 1:20 6x. Esteira/bike 40min", medicamentos: "Deca e durateston", comorbidades: "Não", objetivo: "Qualidade de treino, alimentação e definição", telefone: "21987287948" },
  { timestamp: "4/14/2025", email: "diorgenes93585@gmail.com", full_name: "THIAGO DIORGENES SILVA NETO", peso: "89", nascimento: "39", altura: "177", atividade: "Musculação 1:20 6x. Jiu-jitsu. Caminhada/corrida 20min 1-2x", medicamentos: "Creatina, Whey, Durateston", comorbidades: "Não", objetivo: "Ganhos com qualidade", telefone: "" },
  { timestamp: "4/17/2025", email: "antoniodasilva097@gmail.com", full_name: "Antonio carlos da silva", peso: "", nascimento: "45", altura: "1.8", atividade: "Musculação 1h 5x. Jiu-jitsu 2x. Caminhada 30min 5x", medicamentos: "Durateston", comorbidades: "Nenhuma", objetivo: "Condicionamento físico", telefone: "" },
  { timestamp: "4/19/2025", email: "leoanestesista@gmail.com", full_name: "Leonardo Waldstein de Moura Vidal", peso: "75", nascimento: "45", altura: "", atividade: "Musculação 1h 5-6x", medicamentos: "Whey, creatina, ZMA, vitaminas, NAC", comorbidades: "Asma", objetivo: "Hipertrofia com redução gordura", telefone: "" },
  { timestamp: "4/21/2025", email: "monicareisenf@gmail.com", full_name: "Mônica Reis", peso: "67", nascimento: "39", altura: "165", atividade: "Corrida 4x e musculação 4-5x", medicamentos: "Tacita", comorbidades: "Retirada tumor benigno parede abdominal", objetivo: "Perda de gordura e hipertrofia", telefone: "21973206619" },
  { timestamp: "4/21/2025", email: "elton31.sfp@gmail.com", full_name: "Elton dos Santos Ferreira Pedro", peso: "", nascimento: "", altura: "1.83", atividade: "Musculação 2h 5x. Bike/caminhada 20min 2-3x", medicamentos: "Sim", comorbidades: "Cansaço, falta libido", objetivo: "Qualidade de vida e definição", telefone: "" },
  { timestamp: "4/22/2025", email: "robsonsilva2695@gmail.com", full_name: "Robson Ferreira Silva", peso: "118", nascimento: "45", altura: "188", atividade: "Musculação 2h 4x. Corrida 1h 3x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Sucesso", telefone: "" },
  { timestamp: "4/22/2025", email: "milenansantos150479@gmail.com", full_name: "Milena Nascimento dos Santos", peso: "72.5", nascimento: "46", altura: "1.6", atividade: "Musculação 1:30 4x. Cardio 40min 4x", medicamentos: "Enantato 0.5 semanal", comorbidades: "Não", objetivo: "Corpo definido com volume", telefone: "21994766452" },
  { timestamp: "4/24/2025", email: "fernandavt.rj@gmail.com", full_name: "Fernanda Teixeira Vieira", peso: "76", nascimento: "44", altura: "", atividade: "Musculação 1h 4x. Caminhada 40min diário", medicamentos: "Eutyrox 137", comorbidades: "Não", objetivo: "Secar e definir", telefone: "" },
  { timestamp: "4/26/2025", email: "rodrigonevez@outlook.com", full_name: "Rodrigo neves ribeiro", peso: "122", nascimento: "33", altura: "183", atividade: "Academia 1:30 6x. Cardio pós treino 20min 6x", medicamentos: "Creatina e anabolizantes", comorbidades: "Não", objetivo: "Sucesso juntos", telefone: "11915288982" },
  { timestamp: "4/28/2025", email: "biradogas@icloud.com", full_name: "Ubirajara Santos de oliveira", peso: "116.3", nascimento: "49", altura: "", atividade: "Musculação 1:30-2h 5-6x. Caminhada/hit 40-60min 5-6x", medicamentos: "Hormônio, tadalafila, cafeína, ômega 3, T4, creatina", comorbidades: "Pressão", objetivo: "Atingir objetivo", telefone: "21964842744" },
  { timestamp: "4/28/2025", email: "l.c.magalhaes@hotmail.com", full_name: "Leonardo Cerqueira Magalhães", peso: "95", nascimento: "40", altura: "172", atividade: "Musculação 1h 3x", medicamentos: "Enantato e masteron", comorbidades: "Hipertenso", objetivo: "Emagrecimento e hormônios", telefone: "21964277820" },
  { timestamp: "4/29/2025", email: "diegonapaz@bol.com.br", full_name: "Diego Araújo Coelho", peso: "88", nascimento: "42", altura: "", atividade: "Musculação, futebol, corrida 1:30h 5x. Bike 1:20h 1-2x", medicamentos: "Creatina e enantato", comorbidades: "Retocolite ucerativa", objetivo: "Resultado", telefone: "21991947646" },
  { timestamp: "4/29/2025", email: "stephanykelly0015@gmail.com", full_name: "stephany Kelly de Almeida Gomes", peso: "62.5", nascimento: "35", altura: "1.58", atividade: "Musculação 2h 4x. Esteira 45min 4x", medicamentos: "Não", comorbidades: "Cansaço", objetivo: "Ganhar massa muscular", telefone: "21964399383" },
  { timestamp: "4/29/2025", email: "mariaapbarcelos24@gmail.com", full_name: "MARIA APARECIDA BARCELOS", peso: "62.9", nascimento: "35", altura: "", atividade: "Musculação 1-1:30 4x. Bike/escada 20min 2x", medicamentos: "Gestrinona, creatina, whey", comorbidades: "Endometriose", objetivo: "Definição e massa magra", telefone: "27998563093" },
  { timestamp: "4/29/2025", email: "Patriksoulfari@gmail.com", full_name: "Patrik Soares Pinto", peso: "115", nascimento: "37", altura: "", atividade: "Musculação 1:30 4x. HIT 30min 3x", medicamentos: "Creatina", comorbidades: "NÃO", objetivo: "Emagrecimento, massa e definição", telefone: "27996090949" },
  { timestamp: "4/30/2025", email: "thais.lima163@gmail.com", full_name: "Thaís lima do Amaral Barbosa", peso: "69.85", nascimento: "29", altura: "", atividade: "Musculação 1-2h 3x. Pilates 2x. Step 1h 2x", medicamentos: "Ioimbina, ômega 3, arginina, cafeína", comorbidades: "Não", objetivo: "Excelência no atendimento", telefone: "21988177640" },
  { timestamp: "5/1/2025", email: "juniorcesarsouzamarceno@gmail.com", full_name: "Junior Cesar Souza marceno", peso: "", nascimento: "", altura: "167", atividade: "Musculação 30min 1.5x", medicamentos: "Testosterona", comorbidades: "Nao", objetivo: "Evolução no ganho de massa", telefone: "11985076970" },
  { timestamp: "5/5/2025", email: "deucreziapatricia@gmail.com", full_name: "Deucrezia Patricia dos Santos Souza", peso: "69", nascimento: "49", altura: "1.6", atividade: "Musculação 1h 5x", medicamentos: "Não", comorbidades: "Varizes operada", objetivo: "Bons resultados para saúde", telefone: "21964355504" },
  { timestamp: "5/6/2025", email: "c1980jt@gmail.com", full_name: "Cristiano Jorge Teixeira", peso: "", nascimento: "44", altura: "1.79", atividade: "Musculação 40min 3x. Futebol 1:30-2h 2x", medicamentos: "Enantato 1ml, Creatina 5g", comorbidades: "Não", objetivo: "Diminuir gordura e massa magra", telefone: "21988190885" },
  { timestamp: "5/7/2025", email: "felipe.extrema@hotmail.com", full_name: "FELIPE DE ALVARENGA LOPES", peso: "84", nascimento: "41", altura: "", atividade: "Musculação 1:40 5x. Bike/esteira/elíptico 20min 4x", medicamentos: "Whey, creatina, Ômega 3, Vit C, Enantato", comorbidades: "Nao", objetivo: "Evoluir física e mentalmente", telefone: "35998942175" },
  { timestamp: "5/8/2025", email: "aninhadak51@gmail.com", full_name: "ANA CRISTINA COSTA FAGUNDES", peso: "62.2", nascimento: "32", altura: "", atividade: "Musculação 1h 5x. Esteira 25min 2x", medicamentos: "Injeção anticoncepcional", comorbidades: "Nao", objetivo: "Crescer e secar", telefone: "" },
  { timestamp: "5/9/2025", email: "rodrigolacerda2828@gmail.com", full_name: "Rodrigo Lacerda Barroso Medeiros", peso: "113", nascimento: "38", altura: "", atividade: "Musculação 2.5 anos 5-6x. Caminhada/corrida 20-45min 2-3x", medicamentos: "Enantato, masteron, NAC, vit C, melatonina, anastrozol, natoquinase", comorbidades: "Nenhuma", objetivo: "Apoio constante com hormônios", telefone: "21982756406" },
  { timestamp: "5/12/2025", email: "drjosuelopesbuco@gmail.com", full_name: "Josué Lopes", peso: "116", nascimento: "35", altura: "188", atividade: "Musculação 5x. Caminhada 30min 3x", medicamentos: "Enantato, masteron, trembolona, Monjaro", comorbidades: "Nao", objetivo: "Perder peso e corpo estético", telefone: "1941598808" },
  { timestamp: "5/14/2025", email: "laudiceiaro.cardoso@gmail.com", full_name: "Dina Rodrigues Cardoso", peso: "", nascimento: "37", altura: "", atividade: "Musculação/cardio 1:30 5-6x. Esteira/spinning 40min 3x", medicamentos: "Oxandrolona, whey, creatina, vitaminas", comorbidades: "Não", objetivo: "Definir e perder gordura", telefone: "" },
  { timestamp: "5/16/2025", email: "biancahammond4@gmail.com", full_name: "Bianca Hammond", peso: "63", nascimento: "49", altura: "1.63", atividade: "Musculação 1-1:30 6x. Caminhada/escada 40min 2x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Resultado", telefone: "21964461262" },
  { timestamp: "5/17/2025", email: "ruanmachadi@gmail.com", full_name: "Ruan machado", peso: "", nascimento: "25", altura: "164", atividade: "Musculação 1:20 6x. Esteira hit 15min", medicamentos: "Dura", comorbidades: "Ombro esquerdo ruim", objetivo: "Dieta e protocolo profissional", telefone: "21967213436" },
  { timestamp: "5/17/2025", email: "sylviasargitario79@gmail.com", full_name: "Silvia Ramos de Souza", peso: "", nascimento: "12/9/1979", altura: "", atividade: "Musculação, natação, funcional, vôlei", medicamentos: "Suplemento, vitamina, creatina, pré treino", comorbidades: "Não sei", objetivo: "...", telefone: "21972459222" },
  { timestamp: "5/19/2025", email: "jorgeleandrosantosreis@gmail.com", full_name: "jorge leandro santos reis", peso: "130", nascimento: "7/28/1992", altura: "1.79", atividade: "No momento não", medicamentos: "Não", comorbidades: "Fumante", objetivo: "Ajuda", telefone: "21998240866" },
  { timestamp: "5/19/2025", email: "jpcora@live.com", full_name: "João Paulo Corá Duarte", peso: "96", nascimento: "6/14/1974", altura: "", atividade: "Musculação 30min 4x. Corrida 10min 4x", medicamentos: "Cipionato de testosterona 125mg/semana", comorbidades: "Não", objetivo: "Melhorar condição física", telefone: "13991139706" },
  { timestamp: "5/20/2025", email: "buenojunior008@gmail.com", full_name: "Maurício júnior Bueno de camargo", peso: "95", nascimento: "11/20/1990", altura: "", atividade: "Musculação 90min 4x. Corrida 30min 5x", medicamentos: "Creatina", comorbidades: "Nenhuma", objetivo: "Bom resultado", telefone: "47988282287" },
  { timestamp: "5/21/2025", email: "bsousa1810@gmail.com", full_name: "BRUNO PEREIRA DE SOUSA", peso: "195", nascimento: "10/18/1985", altura: "", atividade: "Musculação 1:30 5x. Esteira 30min 3x", medicamentos: "Mounjaro, creatina, pré treino", comorbidades: "Excesso de peso", objetivo: "Ajuda e orientação", telefone: "21999771820" },
  { timestamp: "5/22/2025", email: "mattosthay28@gmail.com", full_name: "Thayna Esthefany Aguiar De mattos", peso: "", nascimento: "4/28/1997", altura: "", atividade: "Musculação 1:45 5x. Cardio 20-50min diário", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecer", telefone: "21990748702" },
  { timestamp: "5/22/2025", email: "geovanna_toss@outlook.com", full_name: "ANDREA GEOVANNA SILVA TOSS", peso: "57", nascimento: "9/13/1999", altura: "170", atividade: "Musculação 1h 3x. Corrida 30min 3x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecer", telefone: "13996991131" },
  { timestamp: "5/22/2025", email: "paulo.brito81@gmail.com", full_name: "Paulo Roberto Brito Junior", peso: "102", nascimento: "3/25/1981", altura: "183", atividade: "Musculação 90min 5-6x. Caminhada 20min 3-4x", medicamentos: "Durateston, masteron, creatina, cafeína", comorbidades: "Não", objetivo: "Diminuir gordura mantendo massa magra", telefone: "" },
  { timestamp: "5/23/2025", email: "renata2105@gmail.com", full_name: "Renata Andressa da Silva Barcelos", peso: "106", nascimento: "5/21/1977", altura: "172", atividade: "Musculação 1:30 3x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecer com saúde", telefone: "" },
  { timestamp: "5/23/2025", email: "victorvieira_13@hotmail.com", full_name: "Victor Hugo", peso: "79", nascimento: "2/3/1997", altura: "178", atividade: "Musculação 1h 5x. Caminhada/corrida 1h 2x", medicamentos: "Creatina e whey", comorbidades: "Não", objetivo: "Massa muscular e definição", telefone: "11951464694" },
  { timestamp: "5/26/2025", email: "rhcrafa446@gmail.com", full_name: "Rafael coimbra bassetto", peso: "101", nascimento: "1/13/1987", altura: "", atividade: "Musculação 1:30-2h 5x. Bike/corrida 20-30min 3x", medicamentos: "Enantato, trembolona, Masteron", comorbidades: "Pico de pressão alta", objetivo: "Melhor versão", telefone: "11947395857" },
  { timestamp: "5/26/2025", email: "magnussantos123@gmail.com", full_name: "Magnus Costa dos Santos", peso: "85", nascimento: "9/28/1993", altura: "", atividade: "Musculação 40-60min 5x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Bom resultados", telefone: "55999643293" },
  { timestamp: "5/27/2025", email: "isisclemente10@gmail.com", full_name: "Isis de Oliveira Clemente", peso: "86", nascimento: "4/10/1996", altura: "", atividade: "Musculação 2h 5x. Caminhada 40min 5x", medicamentos: "Não", comorbidades: "Tab tipo 1, ansiedade generalizada", objetivo: "Alcançar objetivos", telefone: "31982814972" },
  { timestamp: "5/27/2025", email: "fernandopradoanestesista@gmail.com", full_name: "Fernando Prado", peso: "83", nascimento: "12/12/1977", altura: "175", atividade: "Musculação 1h 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Massa muscular, baixar gordura", telefone: "" },
  { timestamp: "5/27/2025", email: "meiriellesilvathunderr@gmail.com", full_name: "Meirielle Silva de Mendonça", peso: "", nascimento: "10/29/1982", altura: "", atividade: "Musculação 1-1:30 5x", medicamentos: "Creatina, finasterida, biotina, testosterona, Deca", comorbidades: "Dor no joelho, escoliose, lordose cervical", objetivo: "Aumentar massa muscular", telefone: "" },
  { timestamp: "5/29/2025", email: "camilla.maarino2014@gmail.com", full_name: "Camilla Mariano", peso: "67", nascimento: "2/5/1999", altura: "156", atividade: "Musculação 1:30 4x. Bike/escada 20-30min 2x", medicamentos: "Creatina e pré treino", comorbidades: "Asma controlada", objetivo: "Melhorar porte físico", telefone: "19974125168" },
  { timestamp: "5/30/2025", email: "t.r.z.djone2@gmail.com", full_name: "Djone Ferreira de Oliveira", peso: "107", nascimento: "4/27/1993", altura: "185", atividade: "Musculação 1:10 5x. Caminhada 20min 5x", medicamentos: "Enantato 250mg, creatina, albumina", comorbidades: "Nao", objetivo: "Resultado positivo e orientação", telefone: "17982022941" },
  { timestamp: "5/30/2025", email: "tfabio567@gmail.com", full_name: "Fábio Tavares Marques Júnior", peso: "90", nascimento: "5/18/2005", altura: "", atividade: "Handebol 1:30 + musculação 1h 6x", medicamentos: "Whey e creatina", comorbidades: "Não", objetivo: "Melhorar condicionamento", telefone: "" },
  { timestamp: "5/31/2025", email: "silas_nazario@hotmail.com", full_name: "SILAS NAZARIO DE SOUSA", peso: "94", nascimento: "10/12/1989", altura: "175", atividade: "Musculação 1h 6x. Caminhada 45min 5x", medicamentos: "Testo, glicina, gaba, cafeína, ioimbina", comorbidades: "Não", objetivo: "Resultado positivo", telefone: "" },
  { timestamp: "6/1/2025", email: "spezanieng@gmail.com", full_name: "João Roberto Sousa Fernandes", peso: "97.5", nascimento: "6/23/1981", altura: "", atividade: "Musculação 1h 6x. Jiu-jitsu 1:30. Caminhada/corrida 30min 3x", medicamentos: "Enantato 250mg, masteron 200mg", comorbidades: "Não", objetivo: "Orientação e hormônios", telefone: "22974014507" },
  { timestamp: "6/2/2025", email: "marinaoliveira25.mr@gmail.com", full_name: "Marina Rosa de Oliveira", peso: "56", nascimento: "6/4/1988", altura: "159", atividade: "Musculação/cardio 1:30-2h 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Bons resultados", telefone: "21993583317" },
  { timestamp: "6/2/2025", email: "nayanitt@hotmail.com", full_name: "Nayana Pereira Santos", peso: "85", nascimento: "8/16/1989", altura: "160", atividade: "Crossfit 1h 2x. Caminhada 1h 1x", medicamentos: "Não", comorbidades: "Não", objetivo: "Emagrecimento com saúde", telefone: "21993989015" },
  { timestamp: "6/2/2025", email: "lopesjoaomarcos114@gmail.com", full_name: "João marcos Lopes Gonçalves", peso: "", nascimento: "5/6/1994", altura: "", atividade: "Musculação 2h 5x", medicamentos: "Creatina, Whey, Hormônio", comorbidades: "Não", objetivo: "Bom resultados", telefone: "21992373129" },
  { timestamp: "6/3/2025", email: "carolsdmarinho@gmail.com", full_name: "Caroline Marinho Rodrigues da Silva", peso: "79", nascimento: "3/30/1985", altura: "164", atividade: "Bike, musculação esporádica", medicamentos: "Remédio pressão alta", comorbidades: "Não", objetivo: "Perda de peso sem flacidez", telefone: "21964478058" },
  { timestamp: "6/3/2025", email: "moniquedasilvasantos309@gmail.com", full_name: "Monique da Silva Santos", peso: "", nascimento: "1/31/1981", altura: "162", atividade: "Musculação e hits 2h 5x. Corrida/spinning 40min diário", medicamentos: "Creatina, omega3, anabolizante", comorbidades: "Não", objetivo: "Definição e saúde", telefone: "" },
  { timestamp: "6/5/2025", email: "andersonntoscano@gmail.com", full_name: "Anderson Toscano Martins", peso: "", nascimento: "11/1/1982", altura: "177", atividade: "Musculação 1h 3-5x. Caminhada 30min 3x", medicamentos: "Durateston", comorbidades: "Não", objetivo: "Perder barriga e aumentar libido", telefone: "83996304248" },
  { timestamp: "6/5/2025", email: "contato@imoviesroulien.com.br", full_name: "ROULIEN SEGUNDO PINTO CAMILLO", peso: "80", nascimento: "3/1/1979", altura: "1.64", atividade: "Musculação 1h 6x. Caminhada 30-60min diário", medicamentos: "Sim", comorbidades: "Não", objetivo: "Ficar com Shape", telefone: "21964755996" },
  { timestamp: "6/5/2025", email: "josimarlemos81@hotmail.com", full_name: "Josimar oliveira lemos", peso: "85", nascimento: "7/8/1981", altura: "1.76", atividade: "Musculação 1-2h 4-5x. Cardio 40min 1x", medicamentos: "Sim", comorbidades: "Não", objetivo: "Qualidade vida, peso seco", telefone: "27981193258" },
  { timestamp: "6/5/2025", email: "diameryskauana@gmail.com", full_name: "Diamerys Kauanna da Silva Santana", peso: "", nascimento: "4/3/1999", altura: "", atividade: "Musculação 1h 5x", medicamentos: "Não", comorbidades: "Não", objetivo: "Massa muscular e emagrecer", telefone: "83986032705" },
  { timestamp: "6/6/2025", email: "josealexandre@rocketmail.com", full_name: "José Alexandre Paes Freitas", peso: "", nascimento: "3/27/1978", altura: "", atividade: "Musculação 2h 3-5x. Caminhada/bike/escada 30min 3-5x", medicamentos: "Acertalix, concor, velanfaxina, trazodona, suplementos", comorbidades: "Pressão alta, ansiedade", objetivo: "Ganho de massa muscular", telefone: "" },
  { timestamp: "6/10/2025", email: "ursulla.almeida@gmail.com", full_name: "Ursulla Mendonça", peso: "64", nascimento: "11/19/1992", altura: "", atividade: "Musculação 60-70min 5x. Caminhada 20-30min 2-3x", medicamentos: "Oxandrolona, espironolactona", comorbidades: "Rotura total LCA esquerdo e parcial direito", objetivo: "Diminuir gordura e aumentar massa magra", telefone: "21994742604" },
  { timestamp: "6/10/2025", email: "alepeze@gmail.com", full_name: "ALEXANDRE SILVA PEZENATO", peso: "84.3", nascimento: "11/5/1974", altura: "", atividade: "Futebol 60-90min 3-4x", medicamentos: "Para glicose", comorbidades: "Diabetes", objetivo: "Melhorar saúde", telefone: "21985314231" },
  { timestamp: "6/12/2025", email: "danibabyniel@hotmail.com", full_name: "Danielle Silva Marins Lopes", peso: "", nascimento: "8/27/1982", altura: "161", atividade: "Musculação/cardio 2h 5x", medicamentos: "Puran 125 t4", comorbidades: "Não", objetivo: "Resultado avançado", telefone: "" },
];

export function getSpreadsheetStudents(): ParsedStudent[] {
  return rawData.map((r) => ({
    full_name: r.full_name,
    email: r.email,
    phone: cleanPhone(r.telefone),
    weight: parseWeight(r.peso),
    height: parseHeight(r.altura),
    birth_date: parseBirthDate(r.nascimento),
    physical_activity: r.atividade || "...",
    objective: r.objetivo || "...",
    current_protocol: r.medicamentos || "...",
    comorbidities: r.comorbidades || "...",
  }));
}
